name: Build and deploy Node.js app to Azure Web App - spice-delight-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies, build, and test
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_VAULT_URL: ${{ secrets.AZURE_VAULT_URL }}
          VITE_SPICE_DELIGHT_API_URL: ${{ secrets.VITE_SPICE_DELIGHT_API_URL }}
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        # Other scripts if configured should be added here, such as linting, formatting

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: https://spice-delight-app.azurewebsites.net

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: spice-delight-app
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .

      - name: Install PM2
        run: |
          npm install -g pm2

      - name: 'Start the server'
        run: |
          pm2 start server/index.js --name spice-delight-app
